### ISSUE TITLE
html_body does not work

### ISSUE THREAD

**Issue by alipala-ah** [dawidd6/action-send-mail#102]
Hi,

When add the single page report as an html body to outlook email by using a github action, It is seen css codes before the report itself.
My question is why css codes are seen in the report? How can I remove?

![image](https://user-images.githubusercontent.com/99248819/161086728-2ff45da9-e75a-4bc7-95ed-b0622ab084fc.png)

[Single Page Report.zip](https://github.com/serenity-bdd/serenity-core/files/8388656/Single.Page.Report.zip)

I am trying to show such daily report in the email.

This is the code part in .yml file ho I use
![image](https://user-images.githubusercontent.com/99248819/161086860-c2028d10-3ab5-430e-ae1b-515cf4fcd7f4.png)

**Comment by charlie-cadmv** [comment]
My guess is that your answer is at the top of `serenity-summary.html`. Have you considered just printing its content to see if it actually starts with valid html?
If you're running on a Linux-ish OS, you can just:
```yaml
- run: cat -A target/site/serenity/serenity-summary.html
```
That should let you see what's being sent. If it doesn't start with `<DOCTYPE html>` or at least `<html>`, you have your answer.
