### ISSUE TITLE
html_body not working 

### ISSUE THREAD

**Issue by BadisOrf** [dawidd6/action-send-mail#107]
hello, 
i'm about to send an email using github actions , the probleme i want to send a html body in this email ''ENOENT: no such file or directory'' , however the path that i past it is true , i'm also trying with readme.md but i found the same result 
![image](https://user-images.githubusercontent.com/101585208/166439541-922024b1-a07e-47ea-be23-2aac0583a1ca.png)

![image](https://user-images.githubusercontent.com/101585208/166439767-346f09ca-56ed-44ca-b76d-ba59fba2fdf4.png)

**Comment by dawidd6** [comment]
Show the workflow
