### ISSUE TITLE
markdown format support

### ISSUE THREAD

**Issue by btrspg** [dawidd6/action-send-mail#11]
Hi there,

Thanks for providing this email sending action. I am using this in my project now. I wrote my readme in `markdown` format, so I wonder if this could support the `markdown` format in the content.

**Comment by dawidd6** [comment]
I don't think markdown is supported by any mail client. A solution for that would be to simply convert markdown document to HTML and then send it with `content-type: text/html`. If you have other ideas, I can accept a PR.

**Comment by sky-code** [comment]
I think it's good idea to add another parameter `converter: md` for example, that gonna convert md to html, and in future same converter can be added for `rst` and so on.

**Comment by dawidd6** [comment]
If someone wants to pick up on this, please go ahead.
