### ISSUE TITLE
html_body doesn't work - no such file

### ISSUE THREAD

**Issue by gzeng1** [dawidd6/action-send-mail#110]
I use the same file path , the attachment can be uploaded with email. 
But the html_body can not work.

Here is the workflow:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/92835134/167999315-d03faf9f-0a01-4b6d-b415-205ddc4f1a58.png">

**Comment by dawidd6** [comment]
Glob `*` will not work here
