### ISSUE TITLE
How could I set multi-line content in the body part？

### ISSUE THREAD

**Issue by michaeljia2021** [dawidd6/action-send-mail#113]
hello, I want to send an email with long content, I put the content after body, but it reported error if I split the content into multi-line.

body: Email content:
*****************************

Please find the error notification below
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line

**Comment by dhruv92** [comment]
You can use a `|` to pass multiline arguments to yml parameter (https://www.baeldung.com/yaml-multi-line)

```
body: |
  Hi there,
  
  Thanks for reaching out!
  
  Best,
```

**Comment by michaeljia2021** [comment]
@dhruv92 Thanks very much for your help.
