### ISSUE TITLE
Send mail Github Action || Zipped Files are not sent as part of the attachments

### ISSUE THREAD

**Issue by Anshita-Bhasin** [dawidd6/action-send-mail#115]
Sending attachments as a .zip file which is generated using github actions -->  **papeloto/action-zip@v1**

Able to send the single HTML file in email but zipped package is not getting sent. Workflow is running without error but the attachment is missing in the email.

- name: Zip Package
        uses: papeloto/action-zip@v1
        with:
          files: cypress/reports/
          dest: result.zip   
      - name : Upload Artifact    
        uses: actions/upload-artifact@v1
        with:
         name: Test_Cypress_Report
         path: ${{ github.workspace }}/result.zip
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
         username: ${{secrets.MAIL_USERNAME}}
         password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: test@disposable.com
          html_body: cypress/reports/Result/index.html
          from: QA
          body: 'Build job of ${{github.repository}} - Testing Report completed successfully!'
          content_type: application/zip
          attachments: '[{"path":${{ github.workspace }}//result.zip}]'

**Comment by dumidu1998** [comment]
![image](https://user-images.githubusercontent.com/50117273/192142887-9a969af4-1ffa-4cba-9671-c20e3a84ecb4.png)
Im using gmail as mail provider. 
 Getting this error when attaching a zip file.
Any suggestion?

**Comment by charlie-cadmv** [comment]
@Anshita-Bhasin Your `attachments:` value looks wrong to me. Try `attachments: result.zip`.

**Comment by jasonm23** [comment]
This is dependent on email service provider, not a valid issue for the action.
