### ISSUE TITLE
Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [dawidd6/action-send-mail#120]
Hello please help me I got `Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at`

Less secure app access Is on

**Comment by noudadrichem** [comment]
This suddenly happened to me too last week as well. Unable to find a fix. Help is wanted!

**Comment by gcallah** [comment]
It looks to me like no one is supporting this, since all of these issues since July have gone unanswered.

**Comment by dawidd6** [comment]
I support this action whenever I can. If I don't know the answer, then I don't speak out, simple.

**Comment by jasonm23** [comment]
This is indeed very likely upstream and depends on the SMTP service provider policy.

If you are using the url scheme to include auth details, don't use the individual settings described in README
