### ISSUE TITLE
how to embed variables in html body

### ISSUE THREAD

**Issue by ukreddy-erwin** [dawidd6/action-send-mail#123]
i want to insert a table in email.
where the email needs to expand the variables in html body.

how to do that?

**Comment by mschroeder-gpfw** [comment]
If you look at the source code, it never parses the html_body for any variables, they have to be set when you set html_body.  I was able to get both plaintext and html emails working great by just using markdown for the html_body and set the variables there.


    body: |
      ${{github.repository}} » ${{github.ref_name}} - [Build # ${{github.run_number}}][1] - ${{job.status}}

      Commit: ${{github.sha}}

      [1]: ${{ steps.get-job-summary-link.outputs.job_summary_link }}
    html_body: |
      ${{github.repository}} » ${{github.ref_name}} - [Build # ${{github.run_number}}](${{ steps.get-job-summary-link.outputs.job_summary_link }}) - ${{job.status}}

      Commit: **${{github.sha}}**
    convert_markdown: true
