### ISSUE TITLE
Error: 6924:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

### ISSUE THREAD

**Issue by ukreddy-erwin** [dawidd6/action-send-mail#124]
`Error: 6924:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:`

can anyone please suggest how to fix this?

**Comment by joynerar** [comment]
I received the same error when trying to send through AWS SES on port 587. Try using port 465.

**Comment by vdmontero** [comment]
I get the same thing trying to send through smtp.office365.com on port 587. Also, i get a timeout error when switched port to 465

```connect ETIMEDOUT 52.96.184.50:465```

**Comment by dawidd6** [comment]
Thanks for the solution, closing.
