### ISSUE TITLE
Use URL as single input parameter for credentials

### ISSUE THREAD

**Issue by alonbl** [dawidd6/action-send-mail#127]
Hi,

Thank you for the action.

In order to reduce the number of secrets/environment/configuration it would be great if you support receiving a single URL for identity, something like:

  source_url: smtp://{username}:{password}@{server_address}:{server_port}/
  source_url: smtp+starttls://{username}:{password}@{server_address}:{server_port}/

This will allow a single secret called `MAIL_SOURCE_URL` (or anything similar) to be used as atomic identity with complete information.

The rational is that the user/password are tied to the server and server is tied to the port and protocol... so in order to keep a generic workflow we need at least these as configuration, URL notation supports this rational.

Thanks,

**Comment by dawidd6** [comment]
You can submit a PR adding that.

**Comment by alonbl** [comment]
> You can submit a PR adding that.

Done, please have a look.

**Comment by alonbl** [comment]
Hi @dawidd6 ,

I am sorry, the problem was when `secure` was not specified and guessed.

```diff
-            secure = serverPort === "465";
+            secure = serverPort === "465" ? "true" : "false";
```

It should have been string and not boolean as it sets the default of the input.

Sadly, I did not notice the CI part as it runs only on master. I added another test to check the `connection_url`.

Please find updated pull request: https://github.com/dawidd6/action-send-mail/pull/131
I verified that the CI is working.

Thanks for reviewing,
Alon

**Comment by alonbl** [comment]
Hi @dawidd6 ,
Can you please review again?
Everything should be ready.
Thanks!
