### ISSUE TITLE
How to send a group mail and the recipients are only displayed

### ISSUE THREAD

**Issue by lem0nb** [dawidd6/action-send-mail#14]
How to send a group mail and the recipients are only displayed?
Thank you.

**Comment by dawidd6** [comment]
I don't understand what you mean, sorry.

**Comment by lem0nb** [comment]
That is, when sending an email to multiple people, the email of the person who received it only shows his email.

**Comment by lem0nb** [comment]
> I don't understand what you mean, sorry.

That is, when sending an email to multiple people, the email of the person who received it only shows his email.

**Comment by dawidd6** [comment]
You will need to submit a PR for this, as I don't know how to implement what you want.

**Comment by dawidd6** [comment]
Closing as stale.
