### ISSUE TITLE
How to send email dynamically

### ISSUE THREAD

**Issue by saminBee** [dawidd6/action-send-mail#141]
how can i send email to by assigning a variable in 'to:'

**Comment by saminBee** [comment]
I have a solution for this.
For this you have to create a workflow_dispatch, Such as:
on:
  workflow_dispatch:
    inputs:
      mail:
        description: 'Customer Email'
        required: true
Then it will be a manual workflow. Have to provide the mail to dispatch unless it wont run.

to: ${{ github.event.inputs.mail }}, 

by calling the event you can access your dynamic mail

**Comment by jasonm23** [comment]
any `${{ ... }}` github action expression can be used, inputs, outputs, env etc.

**Comment by jasonm23** [comment]
> I have a solution for this. For this you have to create a workflow_dispatch, Such as: on: workflow_dispatch: inputs: mail: description: 'Customer Email' required: true Then it will be a manual workflow. Have to provide the mail to dispatch unless it wont run.
> 
> to: `${{ github.event.inputs.mail }}`,
> 
> by calling the event you can access your dynamic mail
