### ISSUE TITLE
html_body: loss of formatting

### ISSUE THREAD

**Issue by andybeet** [dawidd6/action-send-mail#145]
Firstly this action is great! Works like a charm.

The only quirk i can't figure out is the "html_body" or "body" keyword usage

I have a plain txt file (datapull.txt) that i am using as the html_body. It just has a few lines, each one with a carriage return (\n). I have tried with line feed (\r) also

I use the following in the yml
```
html_body: file://${{github.workspace}}/data-raw/datapull.txt
```

However when i receive the email the body of the txt file comes through as a single line with all carriage returns ignored. Is this because the html_body is expecting an html file?

How can i pass a txt file and preserve carriage returns/line feeds?

**Comment by dawidd6** [comment]
If the file isn't html, then use `body` input.

**Comment by andybeet** [comment]
Thanks, I tried that but it still doesn't preserve the LF/CR.
It simply returns one long string
