### ISSUE TITLE
`SUBJECT` as a env var.

### ISSUE THREAD

**Issue by Rustam-Z** [dawidd6/action-send-mail#163]
I have env var for creating subject. But when i am passing it as `SUBJECT: $SUBJECT` instead I receive $SUBJECT, but not the real content.

**Comment by benjyw** [comment]
https://github.com/dawidd6/action-send-mail/pull/173 may be helpful here (if you can get your subject into a file instead of an env var)

**Comment by dawidd6** [comment]
How about setting the subject like this:

```yaml
subject: ${{env.SUBJECT}}
```

?

**Comment by dawidd6** [comment]
Solutions provided. Closing.
