### ISSUE TITLE
Error: Input required and not supplied: subject

### ISSUE THREAD

**Issue by rsharma2023** [dawidd6/action-send-mail#167]
Getting this error 
Error: Input required and not supplied: subject

supplied input as text, string and variable but error is not resolved:

![image](https://github.com/dawidd6/action-send-mail/assets/121955303/8f3461f3-dec7-4bad-b96b-079633bae1af)

**Comment by rsharma2023** [comment]
@dawidd6

**Comment by dawidd6** [comment]
https://github.com/rsharma2023/sonarqube-analysis/blob/41c6d0a480602c1370f3e1a6837fcb961505cca8/.github/workflows/codeql.yml#L89

`with`...
