### ISSUE TITLE
Error: 140372281395136:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

### ISSUE THREAD

**Issue by octa2599** [dawidd6/action-send-mail#169]
Hi,

I get this error while trying to send an email:

Error: 140372281395136:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

I tested my connections in an openssl terminal and everything works.
This is what I am using in my workflow:
      # Send email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:   
          connection_url: smtp+starttls://${{secrets.USER_MAIL}}:${{secrets.PASSWORD_USER}}@${{secrets.MAIL_SERVER}}:587
          subject: Workflow run
          to: test@gmail.com
          from: Test
          body: Workflow

Does anyone has any idea what could be the issue?
Thanks!

**Comment by joshpeterson** [comment]
I ran into this same error. [This page](https://github.com/openssl/openssl/issues/18291) was helpful to sort it out.

It turns out I had my port numbers wrong. To send from a gmail account, I used the smtp:// URL and port 587.

I hope this helps you @octa2599!

**Comment by dawidd6** [comment]
Solution provided, thanks @joshpeterson. Closing.
