### ISSUE TITLE
gmail

### ISSUE THREAD

**Issue by davidfurrer** [dawidd6/action-send-mail#17]
Is it possible to use this action with gmail? It seems to get blocked.

Thanks :)!

**Comment by deveshchatuphale7** [comment]
Encountered similar issue, I enabled two step verification for my gmail account, Created app password from gmail settings & added generated app password to secrets

**Comment by deveshchatuphale7** [comment]
> 
> 
> Is it possible to use this action with gmail? It seems to get blocked.
> 
> Thanks :)!
Encountered similar issue, I enabled two step verification for my gmail account, Created app password from gmail settings & added generated app password to secrets

**Comment by deveshchatuphale7** [comment]
> 
> 
> Is it possible to use this action with gmail? It seems to get blocked.
> 
> Thanks :)!


Encountered similar issue, I enabled two step verification for my gmail account, Created app password from gmail settings & added generated app password to secrets

**Comment by davidfurrer** [comment]
https://realpython.com/python-send-email/#option-1-setting-up-a-gmail-account-for-development

alternatively one can create a new gmail account and Turn "Allow less secure apps to" ON

**Comment by LinqLover** [comment]
Same issue here, I turned on the "less secure apps" but the CI job always errors with:
```
Run dawidd6/action-send-mail@v2
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ***
    password: ***
    subject: some subject
    body: some body
    to: ***
    from: GitHub CI
    content_type: text/plain
{
  host: 'smtp.gmail.com',
  port: '465',
  secure: true,
  auth: { user: '***', pass: '***' }
}
Error: Invalid login: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbu
534-5.7.14 CSuqNLF2j5fgdfgdfgGqcJcQOamXeW0wCjfn5ErHHYotnz823LmyVore26bn33vTMBmEHFx_
534-5.7.14 WqwFlEQieditedobfuscatedthistoken_dfgApM2dhMQsYsBlfqECMf6yJYaNoeN7L>
534-5.7.14 Please log in via your web browser and then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 129sm6136356qkf.62 - gsmtp
```

Any ideas?

**Comment by LinqLover** [comment]
Update: I created a dummy hotmail account for it, which works.
