### ISSUE TITLE
Remove warning message when username and password aren't used

### ISSUE THREAD

**Issue by tremblaysimon** [dawidd6/action-send-mail#176]
# Context
Related to PR #60 (thank you for that by the way!) that add the possibility to use a smtp server without authentication when using a self-hosted runner. We can see a warning message here when using the action in the log output: 
![image](https://github.com/dawidd6/action-send-mail/assets/5879940/e814dc2f-b7e3-4f2f-83e9-44baab6f1224)

and also in the Annotations section of the workflow run summary:

![image](https://github.com/dawidd6/action-send-mail/assets/5879940/37d4b3d5-7c2a-4dd1-bc0d-7a973b2fa19b)

Warning message:
`Username and password not specified. You should only do this if you are using a self-hosted runner to access an on-premise mail server.
`

# Problem
Normally, a warning message indicates something that should be fixed. Here there is nothing to fix since it's ok to use in certain condition a smtp server without authentication (when using self-hosted runner for example). In the end the user who uses the action will be tricked by the warning message since there is nothing to do to fix that.

# Solution
Remove that warning message. 

What do you think?

**Comment by dawidd6** [comment]
Guess it's fine.
