### ISSUE TITLE
Update to node breaks backwards compatibility

### ISSUE THREAD

**Issue by schlamar** [dawidd6/action-send-mail#194]
We have a Gitea instance with Actions which does not support node20 (yet). So after the change #193 our CI workflows are broken.

Updating node to 20 without increasing the major version breaks backwards compatibility. You should increase the major version (v4) for such a breaking change.

**Comment by dawidd6** [comment]
Pin to release [v3.10.0](https://github.com/dawidd6/action-send-mail/tree/v3.10.0) if you can't run node20 and consider updating your runner to use the newest release.
