### ISSUE TITLE
Response 421-4.7.0 (Try again later)

### ISSUE THREAD

**Issue by kroese** [dawidd6/action-send-mail#196]
A lot of times I get this error from GMail:

```
Server terminates connection. response=421-4.7.0 Try again later, closing connection. (EHLO)
```

It would be really nice to have an option to retry X times (with a 10 second delay or something), so that the action does not fail immediately upon receiving this response.

**Comment by dawidd6** [comment]
Please submit a PR

**Comment by dawidd6** [comment]
@kroese you don't need this feature anymore?
