### ISSUE TITLE
(action-send-email failing !!!!) GitHub Actions: Transitioning from Node 16 to Node 20

### ISSUE THREAD

**Issue by daspmr** [dawidd6/action-send-mail#198]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dawidd6/action-send-mail@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

/home/git/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/git/actions-runner/externals/node20/bin/node)
/home/git/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/git/actions-runner/externals/node20/bin/node)

**Comment by dawidd6** [comment]
![image](https://github.com/dawidd6/action-send-mail/assets/9713907/a53192b0-a223-4073-9c67-2a4f0ec9015f)
