### ISSUE TITLE
Retry on error mechanism

### ISSUE THREAD

**Issue by pPrecel** [dawidd6/action-send-mail#203]
**Description:**

From time to time I got the error:

```
Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect.
```

It looks like something is not ok with creds passed to the action, but it's not. Re-running the failed workflow or this specific step is enough to send mail.

It would be really helpful if the `send-mail` action had a configurable retry mechanism to cover such cases when a step fails with such a dummy error

**Comment by dawidd6** [comment]
Is this PR something you would be happy with?
https://github.com/dawidd6/action-send-mail/pull/197

If not, please submit another PR.

**Comment by pPrecel** [comment]
yes! thanks. I can't wait for the new release :)
