### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by oozman** [dawidd6/action-send-mail#28]
<img width="750" alt="Screen Shot 2021-01-21 at 6 28 55 PM" src="https://user-images.githubusercontent.com/2807969/105338463-8e37f580-5c16-11eb-9916-4ea6c01f7ca0.png">

Do you have an idea how to fix this? Thanks

**Comment by dawidd6** [comment]
Sorry, but without more details I don't even know how.

**Comment by jimfilippou** [comment]
I want to open a PR related to SSL certificates, there is an option to ignore the cert and just move on. This is for testing purposes.
@oozman the error is self explanatory, you can either refresh the cert or ignore it completely for testing purposes.

**Comment by dawidd6** [comment]
Relevant docs I think: https://nodemailer.com/smtp/#3-allow-self-signed-certificates
