### ISSUE TITLE
Hide multiple email addresses from log output

### ISSUE THREAD

**Issue by mcarans** [dawidd6/action-send-mail#30]
If you put more than one email address in to, cc or bcc, the action-send-mail log shows the full email addresses even if it is passed in from a secret (because in the secret, it is comma separated so GitHub Actions doesn't know how to hide the split individual email addresses in the log output).

I think that action-send-mail email addresses should be hidden in the log or there should be an option not to output the log at all.

**Comment by dawidd6** [comment]
Logging removed completely:
https://github.com/dawidd6/action-send-mail/commit/16840503b7fd719fcd1c0e84464812406a30b935

**Comment by dawidd6** [comment]
New 2.5.0 release created.
