### ISSUE TITLE
Problems with sendgrid

### ISSUE THREAD

**Issue by juanformoso** [dawidd6/action-send-mail#35]
Hi, I was wondering if this was tested with Send Grid, I get an error claiming the `from` address is not from a valid Sender (you have to validate an email with them for this), and I think it's because the field is being sent between `<>`

Anyone else with this problem? Anyone know a workaround?

**Comment by dawidd6** [comment]
Can't help. Not using this service. Maybe someone else could chime in.

**Comment by 100ferhas** [comment]
Hi @juanformoso, 
I'm using Sendgrid without issues.

Are you using api_key authentication?

If you do, maybe you have to setup **sender authentication** on Sendgrid to validate the sender domain (the one you write between `<>`), I had this already done and all it's working fine.

Hope it helps!
