### ISSUE TITLE
Send email via SES

### ISSUE THREAD

**Issue by ad-m** [dawidd6/action-send-mail#36]
Hello,

I would like send email via that action using AWS SES API. Do you like support other transport? I would like provide PR for that.

This is about calling `sendEmail` in AWS SDK ( https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property ) eg. via node-mailer transport ( https://nodemailer.com/transports/ses/ ).

Kind regards,

**Comment by dawidd6** [comment]
Sure, submit a PR and we'll see.

**Comment by Moshikolev** [comment]
any news here?

**Comment by dawidd6** [comment]
See the linked PR.
