### ISSUE TITLE
Given gmail is listed in template, provide additional gmail specific instructions for common pain points

### ISSUE THREAD

**Issue by JustinGOSSES** [dawidd6/action-send-mail#43]
I ran into similar problems that I've seen several people have in other issues/questions. Given gmail is used in template, might be worth noting in README that gmail server access will be blocked as "security issue" unless:

1. - "Less Secure" Apps need to be enabled in google profile. Can't find a static link for this, but if you go to google profile settings and put "less secure apps" in the search bar instructions will come up. 
2. - IMAP needs to be enabled in gmail settings are described here: https://support.google.com/mail/answer/7126229?hl=en 
3. - If you the gmail account in question as 2FA enabled, the 2FA password will need to be provided as well, which isn't included in the default template.

After I did the first two steps and switched to an account without 2FA, the GitHubAction worked and I didn't get security messages from google.

**Comment by JustinGOSSES** [comment]
Happy to help with this and submit pull request if useful.

**Comment by dawidd6** [comment]
Please do
