### ISSUE TITLE
How to use this github action to send an HTML email with images embedded inline 

### ISSUE THREAD

**Issue by afrancis-incomm** [dawidd6/action-send-mail#55]
Hi,
I am tying to find a way to send an email from Github action with an image attached inline as part of the body? With cid mechanism ? Please let me know if it is possible to do so using your github action.

**Comment by dawidd6** [comment]
I don't know, haven't tested it. Maybe some other users have some tips.

**Comment by dawidd6** [comment]
Did you try sending the email with pictures as attachments?

**Comment by dawidd6** [comment]
See https://github.com/dawidd6/action-send-mail/pull/75
