### ISSUE TITLE
Make username and password optional for Self-Hosted runner use cases

### ISSUE THREAD

**Issue by droidpl** [dawidd6/action-send-mail#59]
## Context
Related issue: https://github.com/dawidd6/action-send-mail/issues/10

@dawidd6 Thanks for providing this really handy action.

## Problem
I am relating the issue #10 where this was addressed, and I can see a use case where having username/password optional can be really handy. This is for self-hosted runners, where they have access to internal infrastructure and smtp services. In those cases, the smtp server can work without authentication and it's secure from the access through the internet. If this is or it's not a questionable practice within the enterprise environment is something that can be discussed, but certainly there is audience where this may be interesting.

## Solution
I would suggest, and if you agree I am happy to create a PR, that we make username/password optional and put a warning message in the case people do it to make sure they are aware of the risk.

Optionally we can set a boolean parameter to ack that they are doing something that may potentially be insecure if you want to make this more explicit.

## Proposed changes
The changes required would be:
- Remove the required restriction for username/password
- Add a warning message printed on the log
- (Optional) add an ack parameter to explicitly say you want to be using a non authenticated smtp request
- Add documentation to the readme

What are your thoughts? 😸

**Comment by dawidd6** [comment]
Alright. Let's do it. Make a PR please.

**Comment by droidpl** [comment]
@dawidd6 I've added this draft PR https://github.com/dawidd6/action-send-mail/pull/60. Still haven't tested so that is why it's not submitted, but happy to start hearing your thoughts 😸
