### ISSUE TITLE
Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at 15

### ISSUE THREAD

**Issue by hhhaiai** [dawidd6/action-send-mail#82]
## Computer

> linux 

## Error log

```
Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
15
535 5.7.8  https://support.google.com/mail/?p=BadCredentials e20sm228071oow.5 - gsmtp
```

## more info

1. username/password  is true. 
2.  ”Less Secure App“ is enabled.
3.  IMAP is enabled.
4. not open 2FA .

**Comment by curioyang** [comment]
Change another email.  Google is strict.

**Comment by hhhaiai** [comment]
> 
oho, ok thx

**Comment by ArsalanSaleemOx** [comment]
i got it working with gmail. 2FA was enabled.
