### ISSUE TITLE
TLS Error when using smtp.office365.com

### ISSUE THREAD

**Issue by geraldfehringer** [dawidd6/action-send-mail#88]
Error: 140494523365248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

**Comment by davetapley** [comment]
Removing `secure: true` worked for me with AWS SES.

**Comment by alonbl** [comment]
Microsoft is shutting off smtp/imap support in office365, we had the same issue and moved our automation account to gsuite.

**Comment by dawidd6** [comment]
Closing then, thanks for heads up.
